name: CI
on:
  push:
    tags:
      - 'PROD-v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check app version
        id  : appVersion
        env :
          CONTENT: ${{ cat ./package.json }}
        run: |
          echo $CONTENT
