name: CI
on:
  push:
    tags:
      - 'PROD-v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read package.json
        id  : packagejson
        run: |
          echo "JSON=$(tr -cd "[:print:]" < ./package.json)" >> $GITHUB_ENV
      
      - name: Read app version
        id  : version
        run : echo ${{ fromJSON(env.JSON).version }}
      
      - name: GitHub context
        run : echo ${{ github }}

